name: tictok_clone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  font_awesome_flutter: ^10.7.0
  gallery_saver: ^2.3.2
  go_router: ^14.2.0
  google_fonts: ^4.0.4
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  video_player: ^2.8.6
  visibility_detector: ^0.4.0+2
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  cloud_functions: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/
flutter_intl:
  enabled: true
